import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: "column",
        backgroundColor: "#FFFFFF",
        paddingHorizontal: 16,
    },
    userContainer: {
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "center",
        marginBottom: 32,
        marginTop: 32,
    },
    userImage: {
        width: 60,
        height: 60,
        borderRadius: 16,
        marginRight: 8,
    },
    userName: {
        fontFamily: "Roboto-Medium",
        fontWeight: 700,
        fontStyle: "normal",
        fontSize: 13,
        lineHeight: 15,
        color: "#212121",
    },
    userEmail: {
        fontFamily: "Roboto-Regular",
        fontStyle: "normal",
        fontSize: 11,
        lineHeight: 13,
        color: "#212121",
    },
    itemPhoto: {
        width: "100%",
        height: 240,
        borderRadius: 8,
        marginBottom: 8,
    },
    itemTitle: {
        marginBottom: 11,
        fontFamily: "Roboto-Medium",
        fontStyle: "normal",
        fontSize: 16,
        lineHeight: 19,
        color: "#212121",
    },
    commentsAmount: {
        fontFamily: "Roboto-Regular",
        fontSize: 16,
        lineHeight: 19,
        color: "#212121",
    },
    description: {
        paddingBottom: 34,
        flexDirection: "row",
    },
    comments: {
        marginRight: 31,
        flexDirection: "row",
        alignItems: "center",
    },
    location: {
        marginLeft: "auto",
        flexDirection: "row",
        alignItems: "center",
    },
    containerComment: {
        flex: 1,
        backgroundColor: "#FFFFFF",
        paddingHorizontal: 16,
        paddingBottom: 16,
        paddingTop: 32,
    },
    postPhoto: {
        width: "100%",
        height: 240,
        borderRadius: 8,
    },
    commentField: {
        flexDirection: "row",
        marginBottom: 24,
    },
    commentRevercedField: {
        flexDirection: "row-reverse",
        marginBottom: 24,
    },
    authorAvatar: {
        width: 28,
        height: 28,
        borderRadius: 100,
    },
    commentLogin: {
        marginRight: 16,
    },
    commentWrapper: {
        flex: 1,
        padding: 16,
        backgroundColor: "rgba(0, 0, 0, 0.03)",
        borderRadius: 6,
    },
    commentText: {
        marginBottom: 8,
        fontFamily: "Roboto-Regular",
        fontStyle: "normal",
        fontSize: 13,
        lineHeight: 18,
        color: "#212121",
        overflow: "hidden",
    },
    date: {
        fontFamily: "Roboto-Regular",
        fontStyle: "normal",
        fontSize: 10,
        lineHeight: 12,
        color: "#BDBDBD",
    },
    commentInput: {
        padding: 16,
        paddingRight: 58,
        position: "relative",
        height: 50,
        fontFamily: "Roboto-Regular",
        fontSize: 16,
        lineHeight: 19,
        color: "#212121",
        borderWidth: 1,
        borderColor: "#E8E8E8",
        borderStyle: "solid",
        backgroundColor: "#F6F6F6",
        borderRadius: 100,
    },
    commentBtn: {
        position: "absolute",
        bottom: 8,
        right: 8,
        width: 34,
        height: 34,
        borderRadius: 50,
        backgroundColor: "#FF6C00",
        borderWidth: 1,
        borderColor: "#E8E8E8",
        justifyContent: "center",
        alignItems: "center",
    },
});