import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
    },
    bgImage: {
        flex: 1,
        resizeMode: "cover",
        justifyContent: "flex-end",
    },
    wrapper: {
        position: "relative",
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        marginTop: "auto",
        backgroundColor: "#fff",
        paddingTop: 92,
    },
    avatar: {
        position: "absolute",
        alignSelf: "center",
        marginHorizontal: "auto",
        width: 120,
        height: 120,
        backgroundColor: "#F6F6F6",
        borderRadius: 16,
        top: -60,
    },
    avatarImage: {
        width: 120,
        height: 120,
        borderRadius: 16,
    },
    buttonIcon: {
        position: "absolute",
        justifyContent: "center",
        alignItems: "center",
        bottom: 14,
        right: -13,
        width: 25,
        height: 25,
        borderRadius: 50,
        borderWidth: 1,
        borderColor: "#E8E8E8",
    },
    title: {
        fontFamily: "Roboto-Medium",
        fontStyle: "normal",
        fontSize: 30,
        lineHeight: 35,
        letterSpacing: 0.01,
        marginBottom: 33,
        textAlign: "center",
        color: "#212121",
    },
    form: {
        marginHorizontal: 16,
    },
    input: {
        paddingHorizontal: 16,
        borderWidth: 1,
        height: 50,
        borderRadius: 8,
        borderStyle: "solid",
        borderColor: "#E8E8E8",
        backgroundColor: "#F6F6F6",
    },
    inputFocus: {
        borderColor: "#FF6C00",
    },
    btnPassword: {
        position: "absolute",
        right: 16,
        top: 16,
    },
    passwordText: {
        fontFamily: "Roboto-Regular",
        fontStyle: "normal",
        fontWeight: 400,
        textAlign: "right",
        fontSize: 16,
        lineHeight: 19,
        color: "#1B4371",
    },
    button: {
        marginBottom: 16,
        padding: 16,
        alignItems: "center",
        height: 50,
        backgroundColor: "#FF6C00",
        borderRadius: 100,
    },
    buttonText: {
        fontFamily: "Roboto-Regular",
        fontWeight: 400,
        fontStyle: "normal",
        fontSize: 16,
        lineHeight: 19,
        color: "#fff",
    },
    text: {
        fontFamily: "Roboto-Regular",
        fontStyle: "normal",
        fontWeight: 400,
        fontSize: 16,
        lineHeight: 19,
        textAlign: "center",
        color: "#1B4371",
    },
    btnRemoveAvatar: {
        position: "absolute",
        bottom: 14,
        right: -12.5,
        justifyContent: "center",
        alignItems: "center",
        width: 25,
        height: 25,
        backgroundColor: "#FFFFFF",
        borderRadius: 50,
        borderWidth: 1,
        borderStyle: "solid",
        borderColor: "#E8E8E8",
    },
    wrapperLogin: {
        position: "relative",
        marginTop: "auto",
        backgroundColor: "#fff",
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        paddingTop: 32,
    },
    textLogin: {
        fontFamily: "Roboto-Regular",
        fontStyle: "normal",
        fontWeight: 400,
        fontSize: 16,
        lineHeight: 19,
        textAlign: "center",
        color: "#1B4371",
        marginBottom: 79,
    },
});